version: '3.1'
networks:
  docker_network:
services:
  express_web:
    build:
      context: .
    image: express-web
    container_name: express-web
    # command:
    #   - nodemon
    #   - '-L'
    #   - '--inspect=0.0.0.0'
    #   - './bin/www'
    # command: 'sh run.sh'
    volumes:
      - .:/home/www/express-locallibrary
      - /home/www/express-locallibrary/node_modules
    restart: always
    ports:
      - '4000:4000'
      - '80:4000'
      - '9229:9229'
    tty: true
    privileged: true
    links:
      - customise_mongo
    depends_on:
      - customise_mongo
    environment:
      - DOCKER=1
    networks:
      - docker_network
    logging:
      driver: 'json-file'
      options:
        max-size: '2000k'
        max-file: '30'

  customise_mongo:
    image: mongo
    # image: customise-mongo
    # build: config3/mongodb
    container_name: customise-mongo
    command: mongod --config /etc/mongod.conf
    # --logpath /tmp/mongodb/log --dbpath /tmp/mongodb/data --repair --fork --auth
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=root
      # - MONGO_CONFIG_DIR=/etc/
      - MONGO_DATA_DIR=/tmp/mongodb/data
      - MONGO_LOG_DIR=/tmp/mongodb/log
    volumes:
      - $PWD/config3/mongodb/mongod.conf:/etc/mongod.conf
      # - /usr/local/var/mongodb
      - $PWD/config3/mongodb/data:/tmp/mongodb/data
      - $PWD/config3/mongodb/log:/tmp/mongodb/log
    # expose:
    #   - '27017'
    ports:
      - '0.0.0.0:28017:27017'
    tty: true
    privileged: true
    networks:
      - docker_network
