version: '3.1'

services:
  web:
    build:
      context: .
    image: web
    container_name: web
    command:
      - nodemon
      - '-L'
      - '--inspect=0.0.0.0'
      - './bin/www'
    # command: 'sh run.sh'
    volumes:
      - .:/home/www/express-locallibrary
      - /home/www/express-locallibrary/node_modules
    # networks:
    #   - node_network
    restart: always
    ports:
      - '4000:4000'
      - '80:4000'
      - '9229:9229'
    tty: true
    privileged: true
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./db:/data/db
    # ports:
    # - '27017:27017'
    expose:
      - '27017'
# networks:
#   node_network:
